// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2UaDet7n9fmgxa6VoeuD7-2PUKuyka3A',
    appId: '1:1023931889610:web:2753daedc2fe77a9bb8133',
    messagingSenderId: '1023931889610',
    projectId: 'pertemuan9-2de19',
    authDomain: 'pertemuan9-2de19.firebaseapp.com',
    storageBucket: 'pertemuan9-2de19.firebasestorage.app',
    measurementId: 'G-VV8G8R9MM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1yPQxwbs-n4a5CkkAv6VKxnkTspuDPLU',
    appId: '1:1023931889610:android:17e4b17f55629ae8bb8133',
    messagingSenderId: '1023931889610',
    projectId: 'pertemuan9-2de19',
    storageBucket: 'pertemuan9-2de19.firebasestorage.app',
  );
}
